ALTER TABLE PractABD1.personas ADD CONSTRAINT PRIMARY KEY(personaID);
ALTER TABLE PractABD1.cursos ADD CONSTRAINT PRIMARY KEY(cursoID);
ALTER TABLE PractABD1.matriculados_interesados ADD CONSTRAINT PRIMARY KEY(personaID,cursoID);